### ISSUE TITLE
OSError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by lrhlrhlrhlrhlrh** [happinesslz/LION#7]
I met this problem,how to solve it?
Traceback (most recent call last):
  File "train.py", line 7, in <module>
    from test import repeat_eval_ckpt
  File "/home/LRH/3D_detection/LION-main/tools/test.py", line 14, in <module>
    from eval_utils import eval_utils
  File "/home/LRH/3D_detection/LION-main/tools/eval_utils/eval_utils.py", line 8, in <module>
    from pcdet.models import load_data_to_gpu
  File "/home/LRH/3D_detection/LION-main/tools/../pcdet/models/__init__.py", line 6, in <module>
    from .detectors import build_detector
  File "/home/LRH/3D_detection/LION-main/tools/../pcdet/models/detectors/__init__.py", line 1, in <module>
    from .detector3d_template import Detector3DTemplate
  File "/home/LRH/3D_detection/LION-main/tools/../pcdet/models/detectors/detector3d_template.py", line 8, in <module>
    from .. import backbones_2d, backbones_3d, dense_heads, roi_heads
  File "/home/LRH/3D_detection/LION-main/tools/../pcdet/models/backbones_3d/__init__.py", line 12, in <module>
    from .lion_backbone_one_stride import LION3DBackboneOneStride, LION3DBackboneOneStride_Sparse
  File "/home/LRH/3D_detection/LION-main/tools/../pcdet/models/backbones_3d/lion_backbone_one_stride.py", line 7, in <module>
    import torch_scatter
  File "/home/anaconda3/envs/lion/lib/python3.8/site-packages/torch_scatter/__init__.py", line 16, in <module>
    torch.ops.load_library(spec.origin)
  File "/home/LRH/anaconda3/envs/lion/lib/python3.8/site-packages/torch/_ops.py", line 643, in load_library
    ctypes.CDLL(path)
  File "/home/LRH/anaconda3/envs/lion/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
Here are some of my environments:
cuda11.8
torch2.1.0+cu118
spconv-cu116

**Comment by lrhlrhlrhlrhlrh** [comment]
Error caused when I run 'python train.py --cfg_file cfgs/kitti_models/second_with_lion_mamba_64dim.yaml'.

**Comment by happinesslz** [comment]
@lrhlrhlrhlrhlrh  Hi, I think it is caused by the mismatched version. Please make sure these versions of CUDA/CUDNN/Pytorch/torch_scatter are consistent.

**Comment by gaodiqaq** [comment]
@lrhlrhlrhlrhlrh I had the same problem as you, did you solve it?

**Comment by gaodiqaq** [comment]
I've solved it by changing the version of torch-scatter
